# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeansModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('clusters', models.IntegerField()),
                ('init', models.TextField(blank=True, default='kmeans++')),
                ('number_iterations', models.IntegerField()),
                ('verbose', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MachineLearningModels',
        ),
    ]
