# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0002_auto_20171123_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF_IDFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField()),
                ('max_features', models.IntegerField()),
                ('max_df', models.FloatField(default=0.95)),
                ('min_df', models.FloatField(default=2)),
                ('stopwords', models.TextField(default='english')),
                ('elasticsearch_category', models.TextField(default='security')),
            ],
            managers=[
                ('vector', django.db.models.manager.Manager()),
            ],
        ),
    ]
