# Generated by Django 2.0 on 2018-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0002_twitteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTracked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
    ]
