# Generated by Django 2.0 on 2018-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0003_notificationlatest_notificationtracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
