# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0003_tf_idfmodel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tf_idfmodel',
            managers=[
            ],
        ),
    ]
