# Generated by Django 2.0 on 2018-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_webapp', '0004_auto_20180416_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtracked',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
